# Site settings
title: Mauricio Junqueira
description: About Me
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mauricio-mautec.github.io"

# User settings
username: Mauricio Junqueira
user_description: enjoy hacking/optimizing systems and code software at daily basis. very broad interests regarding computer languages and hardware. most of code I write is using C/C++ and lately Python. currently working as back end developer in a startup focused in food market. Like Linux (SuSE, raspbian), vim, makefiles, git, TDD. have software written on Windows using embarcadero's RAD Studio in C++ and Delphi. my primary computer is a mac and I like spending time in Xcode compiling software for iOS. have loads of microcontrolers to code in C. love Python, Arduino, RaspBery Pi and to make IOT devices with them!
user_title: Electrical Engineer / Software Developer
email: mauvis@gmail.com
twitter_username: mauvis
github_username:  mauricio-mautec

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

